spring:
  datasource:
    url: jdbc:mysql://localhost:3306/music_w?serverTimezone=Asia/Shanghai
    data-username: root
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  type-aliases-package: com.example.bedhouseserver.POJO
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8888
