package com.example.bedhouseserver.POJO;

import java.util.Date;

public class Live {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live.customer_id
     *
     * @mbggenerated
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live.bed_id
     *
     * @mbggenerated
     */
    private Integer bedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live.begin_date
     *
     * @mbggenerated
     */
    private Date beginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column live.leave_date
     *
     * @mbggenerated
     */
    private Date leaveDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live.id
     *
     * @return the value of live.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live.id
     *
     * @param id the value for live.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live.customer_id
     *
     * @return the value of live.customer_id
     *
     * @mbggenerated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live.customer_id
     *
     * @param customerId the value for live.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live.bed_id
     *
     * @return the value of live.bed_id
     *
     * @mbggenerated
     */
    public Integer getBedId() {
        return bedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live.bed_id
     *
     * @param bedId the value for live.bed_id
     *
     * @mbggenerated
     */
    public void setBedId(Integer bedId) {
        this.bedId = bedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live.begin_date
     *
     * @return the value of live.begin_date
     *
     * @mbggenerated
     */
    public Date getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live.begin_date
     *
     * @param beginDate the value for live.begin_date
     *
     * @mbggenerated
     */
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column live.leave_date
     *
     * @return the value of live.leave_date
     *
     * @mbggenerated
     */
    public Date getLeaveDate() {
        return leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column live.leave_date
     *
     * @param leaveDate the value for live.leave_date
     *
     * @mbggenerated
     */
    public void setLeaveDate(Date leaveDate) {
        this.leaveDate = leaveDate;
    }
}