package com.example.bedhouseserver.POJO;

import java.util.Date;

public class Notice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.release_id
     *
     * @mbggenerated
     */
    private Integer releaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.accept_id
     *
     * @mbggenerated
     */
    private Integer acceptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.notice_time
     *
     * @mbggenerated
     */
    private Date noticeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice.notice_text
     *
     * @mbggenerated
     */
    private String noticeText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.id
     *
     * @return the value of notice.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.id
     *
     * @param id the value for notice.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.release_id
     *
     * @return the value of notice.release_id
     *
     * @mbggenerated
     */
    public Integer getReleaseId() {
        return releaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.release_id
     *
     * @param releaseId the value for notice.release_id
     *
     * @mbggenerated
     */
    public void setReleaseId(Integer releaseId) {
        this.releaseId = releaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.accept_id
     *
     * @return the value of notice.accept_id
     *
     * @mbggenerated
     */
    public Integer getAcceptId() {
        return acceptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.accept_id
     *
     * @param acceptId the value for notice.accept_id
     *
     * @mbggenerated
     */
    public void setAcceptId(Integer acceptId) {
        this.acceptId = acceptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.notice_time
     *
     * @return the value of notice.notice_time
     *
     * @mbggenerated
     */
    public Date getNoticeTime() {
        return noticeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.notice_time
     *
     * @param noticeTime the value for notice.notice_time
     *
     * @mbggenerated
     */
    public void setNoticeTime(Date noticeTime) {
        this.noticeTime = noticeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice.notice_text
     *
     * @return the value of notice.notice_text
     *
     * @mbggenerated
     */
    public String getNoticeText() {
        return noticeText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice.notice_text
     *
     * @param noticeText the value for notice.notice_text
     *
     * @mbggenerated
     */
    public void setNoticeText(String noticeText) {
        this.noticeText = noticeText == null ? null : noticeText.trim();
    }
}