package com.example.bedhouseserver.POJO;

import java.util.Objects;

public class NursingLevelContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nursing_level_content.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nursing_level_content.level_id
     *
     * @mbggenerated
     */
    private Integer levelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nursing_level_content.content_id
     *
     * @mbggenerated
     */
    private Integer contentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nursing_level_content.id
     *
     * @return the value of nursing_level_content.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nursing_level_content.id
     *
     * @param id the value for nursing_level_content.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nursing_level_content.level_id
     *
     * @return the value of nursing_level_content.level_id
     *
     * @mbggenerated
     */
    public Integer getLevelId() {
        return levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nursing_level_content.level_id
     *
     * @param levelId the value for nursing_level_content.level_id
     *
     * @mbggenerated
     */
    public void setLevelId(Integer levelId) {
        this.levelId = levelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nursing_level_content.content_id
     *
     * @return the value of nursing_level_content.content_id
     *
     * @mbggenerated
     */
    public Integer getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nursing_level_content.content_id
     *
     * @param contentId the value for nursing_level_content.content_id
     *
     * @mbggenerated
     */
    public void setContentId(Integer contentId) {
        this.contentId = contentId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        NursingLevelContent that = (NursingLevelContent) o;
        return Objects.equals(id, that.id) && Objects.equals(levelId, that.levelId) && Objects.equals(contentId, that.contentId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, levelId, contentId);
    }
}