package com.example.bedhouseserver.POJO;

import java.util.Date;
import java.util.Objects;

public class NursingRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nursing_record.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nursing_record.stf_id
     *
     * @mbggenerated
     */
    private Integer stfId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nursing_record.customer_id
     *
     * @mbggenerated
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nursing_record.nursing_content_id
     *
     * @mbggenerated
     */
    private Integer nursingContentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nursing_record.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nursing_record.id
     *
     * @return the value of nursing_record.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nursing_record.id
     *
     * @param id the value for nursing_record.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nursing_record.stf_id
     *
     * @return the value of nursing_record.stf_id
     *
     * @mbggenerated
     */
    public Integer getStfId() {
        return stfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nursing_record.stf_id
     *
     * @param stfId the value for nursing_record.stf_id
     *
     * @mbggenerated
     */
    public void setStfId(Integer stfId) {
        this.stfId = stfId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nursing_record.customer_id
     *
     * @return the value of nursing_record.customer_id
     *
     * @mbggenerated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nursing_record.customer_id
     *
     * @param customerId the value for nursing_record.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nursing_record.nursing_content_id
     *
     * @return the value of nursing_record.nursing_content_id
     *
     * @mbggenerated
     */
    public Integer getNursingContentId() {
        return nursingContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nursing_record.nursing_content_id
     *
     * @param nursingContentId the value for nursing_record.nursing_content_id
     *
     * @mbggenerated
     */
    public void setNursingContentId(Integer nursingContentId) {
        this.nursingContentId = nursingContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nursing_record.date
     *
     * @return the value of nursing_record.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nursing_record.date
     *
     * @param date the value for nursing_record.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        NursingRecord that = (NursingRecord) o;
        return Objects.equals(id, that.id) && Objects.equals(stfId, that.stfId) && Objects.equals(customerId, that.customerId) && Objects.equals(nursingContentId, that.nursingContentId) && Objects.equals(date, that.date);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, stfId, customerId, nursingContentId, date);
    }
}