package com.example.bedhouseserver.POJO;

import java.util.Date;

public class ServicePurchase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_purchase.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_purchase.customer_id
     *
     * @mbggenerated
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_purchase.nursing_id
     *
     * @mbggenerated
     */
    private Integer nursingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_purchase.purchase_da
     *
     * @mbggenerated
     */
    private Date purchaseDa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_purchase.effective_t
     *
     * @mbggenerated
     */
    private Date effectiveT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_purchase.id
     *
     * @return the value of service_purchase.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_purchase.id
     *
     * @param id the value for service_purchase.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_purchase.customer_id
     *
     * @return the value of service_purchase.customer_id
     *
     * @mbggenerated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_purchase.customer_id
     *
     * @param customerId the value for service_purchase.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_purchase.nursing_id
     *
     * @return the value of service_purchase.nursing_id
     *
     * @mbggenerated
     */
    public Integer getNursingId() {
        return nursingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_purchase.nursing_id
     *
     * @param nursingId the value for service_purchase.nursing_id
     *
     * @mbggenerated
     */
    public void setNursingId(Integer nursingId) {
        this.nursingId = nursingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_purchase.purchase_da
     *
     * @return the value of service_purchase.purchase_da
     *
     * @mbggenerated
     */
    public Date getPurchaseDa() {
        return purchaseDa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_purchase.purchase_da
     *
     * @param purchaseDa the value for service_purchase.purchase_da
     *
     * @mbggenerated
     */
    public void setPurchaseDa(Date purchaseDa) {
        this.purchaseDa = purchaseDa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column service_purchase.effective_t
     *
     * @return the value of service_purchase.effective_t
     *
     * @mbggenerated
     */
    public Date getEffectiveT() {
        return effectiveT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column service_purchase.effective_t
     *
     * @param effectiveT the value for service_purchase.effective_t
     *
     * @mbggenerated
     */
    public void setEffectiveT(Date effectiveT) {
        this.effectiveT = effectiveT;
    }
}