package com.example.bedhouseserver.mapper;

import com.example.bedhouseserver.POJO.Customer;
import org.springframework.stereotype.Repository;

@Repository
public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated
     */
    int insertSelective(Customer record);
}