package com.example.bedhouseserver.mapper;

import com.example.bedhouseserver.POJO.Live;
import com.example.bedhouseserver.POJO.LiveWithCustomerName;
import org.apache.catalina.LifecycleState;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface LiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live
     *
     * @mbggenerated
     */
    int insert(Live record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live
     *
     * @mbggenerated
     */
    int insertSelective(Live record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live
     *
     * @mbggenerated
     */
    Live selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Live record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table live
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Live record);

    Integer getUsedBedIdByCustomerId(@Param("id")Integer id);

    Integer getUsedCustomerIdByBedId(@Param("id")Integer id);

    List<LiveWithCustomerName> allInfo();

    List<LiveWithCustomerName> search(@Param("num")Integer num,@Param("fromDate")String fromDate,@Param("toDate")String toDate);
}