package com.example.bedhouseserver.mapper;

import com.example.bedhouseserver.POJO.NursingContent;

public interface NursingContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nursing_content
     *
     * @mbggenerated
     */
    int insert(NursingContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nursing_content
     *
     * @mbggenerated
     */
    int insertSelective(NursingContent record);
}