package com.example.bedhouseserver.mapper;

import com.example.bedhouseserver.POJO.OutRecord;

public interface OutRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_record
     *
     * @mbggenerated
     */
    int insert(OutRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_record
     *
     * @mbggenerated
     */
    int insertSelective(OutRecord record);
}