package com.example.bedhouseserver.mapper;

import com.example.bedhouseserver.POJO.OutRecord;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

@Mapper
public interface OutRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_record
     *
     * @mbggenerated
     */
    int insert(OutRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_record
     *
     * @mbggenerated
     */
    int insertSelective(OutRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_record
     *
     * @mbggenerated
     */
    OutRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OutRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table out_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OutRecord record);

    List<OutRecord> allInfo();

    List<OutRecord> allNoCheckedInfo();

    List<OutRecord> searchByString(@Param("word") String word, @Param("Date") String date);

    List<OutRecord> searchByNum(@Param("num") Integer num, @Param("Date") String date);

    List<OutRecord> searchNoCheckedByString(@Param("word") String word, @Param("Date") String date);

    List<OutRecord> searchNoCheckedByNum(@Param("num") Integer num, @Param("Date") String date);

    int noCheckedCount();
}