package com.example.bedhouseserver.mapper;

import com.example.bedhouseserver.POJO.Recipes;

public interface RecipesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recipes
     *
     * @mbggenerated
     */
    int insert(Recipes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recipes
     *
     * @mbggenerated
     */
    int insertSelective(Recipes record);
}