package com.example.bedhouseserver.mapper;

import com.example.bedhouseserver.POJO.Recipes;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface RecipesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recipes
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recipes
     *
     * @mbggenerated
     */
    int insert(Recipes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recipes
     *
     * @mbggenerated
     */
    int insertSelective(Recipes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recipes
     *
     * @mbggenerated
     */
    Recipes selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recipes
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Recipes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recipes
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Recipes record);

    List<Recipes> allInfo();

    List<Recipes> searchByString(@Param("word") String word);

    List<Recipes> searchByNum(@Param("num") int num);
}