package com.example.bedhouseserver.mapper;

import com.example.bedhouseserver.POJO.ServicePurchase;
import org.springframework.stereotype.Repository;

@Repository
public interface ServicePurchaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_purchase
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_purchase
     *
     * @mbggenerated
     */
    int insert(ServicePurchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_purchase
     *
     * @mbggenerated
     */
    int insertSelective(ServicePurchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_purchase
     *
     * @mbggenerated
     */
    ServicePurchase selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_purchase
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ServicePurchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_purchase
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ServicePurchase record);
}