package com.example.bedhouseserver.mapper;

import com.example.bedhouseserver.POJO.ServicePurchase;

public interface ServicePurchaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_purchase
     *
     * @mbggenerated
     */
    int insert(ServicePurchase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_purchase
     *
     * @mbggenerated
     */
    int insertSelective(ServicePurchase record);
}